### ISSUE TITLE
메인화면 UI 개선하기

### ISSUE THREAD

**Issue by jsh9611** [Team-BUNT/ClassManager#12]
## 이슈 개요
- ClassCalendarView의 UI를 개선합니다.

## 마감 일자
10월 24일 오후 6시

## Todo List
- [x] Main 앞이나 뒤에 Hall 이라는 것을 명시
- [x] "링크 복사" 버튼을 눌렀을 때 토스트 메시지 색깔 변경
- [x] 하단 리스트의 박스에서 chevron.right">" 추가하기
- [x] 하단 리스트의 박스에서 시간의 위치를 변경
