### ISSUE TITLE
신청내역UI 개선 및 로직 개선

### ISSUE THREAD

**Issue by jsh9611** [Team-BUNT/ClassManager#13]
## 이슈 개요
- EnrollmentListView의 UI를 개선합니다.
- 신청내역에서 보여지는 리스트의 로직을 개선합니다.

## 마감 일자
10월 24일 오후 6시

## Todo List
- [x] 홀 이름 뒤에 "홀"을 붙이기
- [x] 연락처 왼쪽정렬
- [x] 패딩값을 피그마에 맞게 적용
- [x] 상단 박스에서 두줄로 읽히면 안됨
- [x] “< Back”에서 “Back”을 지움
- [x] 결제 대기가 맨 위로, 결제 완료가 아래로, 숫자 전체는 큰 수부터 나오도록 로직을 변경
