### ISSUE TITLE
클래스 추가 화면에서 사용자 경험 개선

### ISSUE THREAD

**Issue by jsh9611** [Team-BUNT/ClassManager#14]
## 이슈 개요
- 클래스 추가 화면에서 유저 사용성을 개선합니다.
- 인간 백앤드를 쉽게 할 수 있도록 classID를 “댄서이름 10-20-23:59" 형태로 저장합니다.

## 마감 일자
10월 24일 오후 6시 까지

## Todo List
- [x] Title, Instructor 부분 변경
  - 기존 Text + TextField 였던 것을 TextField와 placeholder 형태로 변경.
  - 기존 텍스트(Title/Instructor)를 "댄서이름/장르"로 변경.
- [x] 수업 시간 관련
  - "분" 부분이 터치가 잘 될 수 있도록 변경
  - "분"앞에 placeholder를 추가 ex) 60
- [x] #22
- [x] Firebase에 저장될 classes의 classID를 "이름 mm-dd-HH:mm" 형태로 저장
- [x] 시간을 눌렀을 때 하프 시트가 올라와서 시간을 설정할 수 있도록 변경이 필요함.(스크린샷 참고)

## 참고
<img src = "https://user-images.githubusercontent.com/57349859/197545496-8154a3c2-74e3-4966-8bff-99ed32d000db.png" width="20%" height="20%">
