### ISSUE TITLE
결제 현황 화면 구현

### ISSUE THREAD

**Issue by namgeon1106** [Team-BUNT/ClassManager#25]
## 이슈 개요
* 결제 내역을 확인하는 화면
* Firebase로부터 수업 신청 데이터 받아와서 화면에 보여줌
* 검색 바에 입력 시 수강생 성명으로 필터링

## 마감 일자
2022.11.7

## 피그마 캡쳐
<img width="216" alt="스크린샷 2022-11-04 오후 4 42 22" src="https://user-images.githubusercontent.com/40821203/199919287-87acd067-9e64-4552-8e80-a23fbc58b1cf.png">

## Todo List
- [x] 검색 바 UI 구현
- [x] 테이블 UI 구현
- [x] 검색 바 필터링 구현
- [x] 파이어베이스 연동
