### ISSUE TITLE
출석 뷰 구현

### ISSUE THREAD

**Issue by Cap0011** [Team-BUNT/ClassManager#27]
## 이슈 개요
출석 뷰 구현

## 마감 일자
2022.11.08

## Todo List
- [x] 클래스 수정 뷰로 연결
- [x] 휴강 시 다른 뷰 적용
- [x] 클래스 삭제 로직 구현
- [x] 휴강 뷰로 연결
- [x] 해당 클래스의 수강생 목록 파이어베이스에서 끌고 오는 로직 구현
- [x] 출결 관리 뷰 구현
- [x] 출석 상태 파이어베이스에 반영하는 로직 구현
- [x] 액션 시트 분기 처리
