### ISSUE TITLE
휴강 사유 뷰 구현

### ISSUE THREAD

**Issue by Cap0011** [Team-BUNT/ClassManager#28]
## 이슈 개요
휴강 사유 뷰 구현

## 마감 일자
2022.11.08

## Todo List
- [x] 휴강 사유 라디오 버튼 뷰 구현 (지오)
- [x] 파이어베이스 휴강 클래스 리스트에 해당 클래스 아이디 추가 (지오)
- [x] 카카오 알림톡과 연결 (안토니)

**Comment by jsh9611** [comment]
구현 완료
