### ISSUE TITLE
추가 피처 구현 전 디테일 및 예외 처리

### ISSUE THREAD

**Issue by Cap0011** [Team-BUNT/ClassManager#39]
## 이슈 개요
추가 피처 구현 전 디테일 및 예외 처리

## 마감 일자
2022.11.16

## Todo List
- [x] AddClassView 반복 횟수 옵션 변경
- [x] AddClassView 반복 레이블 변경
- [x] 정규/팝업 클래스 디자인 구분
- [x] 선택 시간대에 이미 존재하는 클래스가 있다면 추가/수정 막기
