### ISSUE TITLE
로그인 뷰 및 자동 로그인 구현

### ISSUE THREAD

**Issue by namgeon1106** [Team-BUNT/ClassManager#43]
## 이슈 개요
* 로그인 화면 및 기능 구현
* 자동 로그인 구현

## 마감 일자
2022.11.22

## Todo List
- [x] 로그인 화면 UI 구현
- [x] firebase 통한 로그인 구현
- [x] 자동 로그인 구현
