### ISSUE TITLE
수강생 환불 사유 기능 구현

### ISSUE THREAD

**Issue by Cap0011** [Team-BUNT/ClassManager#47]
## 이슈 개요
수강생 환불 사유 기능 구현

## 마감 일자
2022.11.23

## Todo List
- [x] 환불 여부 뷰 추가
- [x] 환불 사유 뷰 추가
- [x] 환불 정보 파이어베이스에 저장
- [x] 환불한 수강생 출석부에서 제외
